TASK_RESULT_FIBER = "FIBER"
TASK_RESULT_SCORCH = "SCORCH"
TASK_RESULT_CAKING = "CAKING"
TASK_RESULT_OTHERS = "OTHERS"

TASK_RESULT_CHOICES = [
    (TASK_RESULT_FIBER, "FIBER"),
    (TASK_RESULT_SCORCH, "SCORCH"),
    (TASK_RESULT_CAKING, "CAKING"),
    (TASK_RESULT_OTHERS, "OTHERS"),
]


CASE_STATUS_PENDING = "PENDING"
CASE_STATUS_RESOLVED = "RESOLVED"

CASE_STATUS_CHOICES = [
    (CASE_STATUS_PENDING, "PENDING"),
    (CASE_STATUS_RESOLVED, "RESOLVED"),
]