CATEGORY_FIBER = "FIBER"
CATEGORY_SCORCH = "SCORCH"
CATEGORY_CAKING = "CAKING"
CATEGORY_OTHERS = "OTHERS"

CATEGORY_CHOICES = [
    (CATEGORY_FIBER, "FIBER"),
    (CATEGORY_SCORCH, "SCORCH"),
    (CATEGORY_CAKING, "CAKING"),
    (CATEGORY_OTHERS, "OTHERS"),
]

CATEGORY_LIST = [
    CATEGORY_FIBER,
    CATEGORY_SCORCH,
    CATEGORY_CAKING,
    CATEGORY_OTHERS,
]


# ========== 狀態 ==========
CASE_STATUS_PENDING = "PENDING"
CASE_STATUS_RESOLVED = "RESOLVED"

CASE_STATUS_CHOICES = [
    (CASE_STATUS_PENDING, "PENDING"),
    (CASE_STATUS_RESOLVED, "RESOLVED"),
]


# ========== 產品問題 ==========
PRODUCT_ISSUE_PKG_INFO = "PACKAGE_INFO" # 包裝上的資訊
PRODUCT_ISSUE_PKG_DAMAGED = "PACKAGE_DAMAGED" # 包裝受損
PRODUCT_ISSUE_SENSUAL = "SENSUOUS" # 感官的
PRODUCT_ISSUE_FOREIGN_MATTER = "FOREIGN_MATTER" # 異物
PRODUCT_ISSUE_AMOUNT = "AMOUNT" # 重量/體積/數量
PRODUCT_ISSUE_OTHERS = "OTHERS"

PRODUCT_ISSUE_CHOICES = [
    (PRODUCT_ISSUE_PKG_INFO, "PACKAGE_INFO"),
    (PRODUCT_ISSUE_PKG_DAMAGED, "PACKAGE_DAMAGED"),
    (PRODUCT_ISSUE_SENSUAL, "SENSUOUS"),
    (PRODUCT_ISSUE_FOREIGN_MATTER, "FOREIGN_MATTER"),
    (PRODUCT_ISSUE_AMOUNT, "AMOUNT"),
    (PRODUCT_ISSUE_OTHERS, "OTHERS"),
]


# ========== 產品名稱 ==========
"""
    Todos:
    1. put produt names into a separate table
    2. use this table as choices for `product_name`
"""
PRODUCT_NAME_ILLUMA_1 = "ILLUMA_1"
PRODUCT_NAME_ILLUMA_3 = "ILLUMA_3"
PRODUCT_NAME_ILLUMA_4 = "ILLUMA_4"
PRODUCT_NAME_ILLUMA_GOAT_3 = "ILLUMA_GOAT_3"
PRODUCT_NAME_ILLUMA_GREEN_1 = "ILLUMA_GREEN_1"
PRODUCT_NAME_ILLUMA_PDF = "ILLUMA_PDF"
PRODUCT_NAME_ILLUMA_HA = "ILLUMA_HA"

PRODUCT_NAME_PGSG = "PGSG"

PRODUCT_NAME_PROCAL_1 = "PROCAL_1"
PRODUCT_NAME_PROCAL_3 = "PROCAL_3"

PRODUCT_NAME_PROGROWTH_1 = "PROGROWTH_1"
PRODUCT_NAME_PROGROWTH_3 = "PROGROWTH_3"
PRODUCT_NAME_PROGROWTH_4 = "PROGROWTH_4"

PRODUCT_NAME_SMAG = "SMAG"

PRODUCT_NAME_ULTIMA_1 = "ULTIMA_1"
PRODUCT_NAME_ULTIMA_1_PRO_2 = "ULTIMA_1_PRO_2"
PRODUCT_NAME_ULTIMA_3 = "ULTIMA_3"
PRODUCT_NAME_ULTIMA_3_PRO_2 = "ULTIMA_3_PRO_2"

PRODUCT_NAME_OTHERS = "OTHERS"