RESULT_FIBER = "FIBER"
RESULT_SCORCH = "SCORCH"
RESULT_CAKING = "CAKING"
RESULT_OTHERS = "OTHERS"

RESULT_CHOICES = [
    (RESULT_FIBER, "FIBER"),
    (RESULT_SCORCH, "SCORCH"),
    (RESULT_CAKING, "CAKING"),
    (RESULT_OTHERS, "OTHERS"),
]