# Generated by Django 4.1.7 on 2023-04-24 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('case_id', models.CharField(max_length=16)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('RESOLVED', 'RESOLVED')], default='PENDING', max_length=16)),
                ('product_name', models.CharField(max_length=16)),
                ('batch_no', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'case',
            },
        ),
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='')),
                ('category', models.CharField(blank=True, choices=[('FIBER', 'FIBER'), ('SCORCH', 'SCORCH'), ('CAKING', 'CAKING'), ('OTHERS', 'OTHERS')], max_length=32, null=True)),
                ('result', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_set', to='cases.casemodel')),
            ],
            options={
                'db_table': 'task',
            },
        ),
    ]
