# Generated by Django 4.1.7 on 2023-04-30 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='img',
            field=models.ImageField(upload_to='tasks/'),
        ),
    ]
