# Generated by Django 4.1.7 on 2023-04-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseresultmodel',
            name='category',
            field=models.CharField(choices=[('FIBER', 'FIBER'), ('SCORCH', 'SCORCH'), ('CAKING', 'CAKING'), ('OTHERS', 'OTHERS')], default='bugs', max_length=32),
        ),
    ]
